version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: rag_backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHROMA_PERSIST_DIR=/app/chroma_db
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/uploads:/app/uploads
      - chroma_data:/app/chroma_db
    networks:
      - rag_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: rag_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - rag_network
    restart: unless-stopped

volumes:
  chroma_data:

networks:
  rag_network:
    driver: bridge